/*
  This file was generated by the Introjucer and is part of Roboverb

  Roboverb: robotic voice and ambience audio effect
  Copyright (C) 2015  Kushview, LLC.  All rights reserved.

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef __JUCE_HEADER_B2E1525EBEE5DE40__
#define __JUCE_HEADER_B2E1525EBEE5DE40__

//[Headers]     -- You can add your own extra header files here --
#include "JuceHeader.h"
//[/Headers]



//==============================================================================
/**
                                                                    //[Comments]
    An auto-generated component, created by the Introjucer.

    Describe your class and how it works here!
                                                                    //[/Comments]
*/
class AboutBox  : public Component
{
public:
    //==============================================================================
    AboutBox ();
    ~AboutBox();

    //==============================================================================
    //[UserMethods]     -- You can add your own custom methods in this section.
    void mouseDown (const MouseEvent& ev) override;
    void setPluginName (const String& name);
    void setPluginVersion (const String& versionString);
    void setPluginUrl (const String& text, const String& url);
    //[/UserMethods]

    void paint (Graphics& g);
    void resized();



private:
    //[UserVariables]   -- You can add your own custom variables in this section.
    String pluginUrl;
    //[/UserVariables]

    //==============================================================================
    ScopedPointer<Label> pluginLabel;
    ScopedPointer<Label> versionLabel;
    ScopedPointer<HyperlinkButton> linkButton;


    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (AboutBox)
};

//[EndFile] You can add extra defines here...
//[/EndFile]

#endif   // __JUCE_HEADER_B2E1525EBEE5DE40__
