#!/bin/bash

# This file is part of Roboverb
# Copyright (C) 2015  Kushview, LLC.  All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

here=`pwd`
version="1.0.4"

set -e

rm -rf build

cd roboverb/Builds/MacOSX
xcodebuild clean build -project Roboverb.xcodeproj -configuration 'Release'
xcodebuild clean build -project Roboverb.xcodeproj -configuration 'Demo'

cd "${here}/standalone/Builds/MacOSX"
xcodebuild clean build -project Roboverb.xcodeproj -configuration 'Release'
xcodebuild clean build -project Roboverb.xcodeproj -configuration 'Demo'

cd "${here}/installers/packages"
rm -rf build/
/usr/local/bin/packagesbuild -v Roboverb.pkgproj
/usr/local/bin/packagesbuild -v RoboverbDemo.pkgproj

cd build
mkdir Roboverb-OSX-${version} RoboverbDemo-OSX-${version}
cp -r Roboverb-OSX-${version}.pkg Roboverb-OSX-${version}/
zip -rT Roboverb-OSX-${version}.zip Roboverb-OSX-${version}
rm -rf Roboverb-OSX-${version}

cp -r RoboverbDemo-OSX-${version}.pkg RoboverbDemo-OSX-${version}/
zip -rT RoboverbDemo-OSX-${version}.zip RoboverbDemo-OSX-${version}
rm -rf RoboverbDemo-OSX-${version}

rm -f *.pkg *.mpkg

cd "$here"
